import "./globals.css";
import Navbar from "./constants/Navbar";
import Footer from "./constants/Footer";
// import localFont from 'next/font/local'

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

// const Montserrat = localFont({
//   src: [
//     { path: './fonts/static/Montserrat-Light.ttf',      weight: '300', style: 'normal' },
//     { path: './fonts/static/Montserrat-Black.ttf',             weight: '400', style: 'normal' },
//     { path: './fonts/static/Montserrat-Medium.ttf',      weight: '500', style: 'normal' },
//     { path: './fonts/static/Montserrat-Bold.ttf',        weight: '700', style: 'normal' },
//     { path: './fonts/static/Montserrat-ExtraBold.ttf',   weight: '800', style: 'normal' },
//   ],
//   variable: '--font-montserrat',
// })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}