import "./globals.css";
import Navbar from "./constants/Navbar";
import Footer from "./constants/Footer";
import ScrollIndicator from "./home/components/ScrollIndicator";
// import localFont from 'next/font/local'

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Navbar/>
        {children}
        <Footer/>
        <ScrollIndicator/>
      </body>
    </html>
  )
}